version: "3"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=newsletter
    ports:
      - 5432:5432
    command: "postgres -N 1000"

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    ports:
      - 3000:8080
