version: "3"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=newsletter
    ports:
      - 5433:5432
    command: "postgres -c max_connections=1000"

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080
